# Generated by Django 4.1.6 on 2025-07-25 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='종목 코드')),
                ('company_name', models.CharField(max_length=100, verbose_name='회사명')),
            ],
            options={
                'verbose_name': '주식 종목',
                'verbose_name_plural': '주식 종목',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('open_price', models.FloatField(verbose_name='시가')),
                ('high_price', models.FloatField(verbose_name='고가')),
                ('low_price', models.FloatField(verbose_name='저가')),
                ('close_price', models.FloatField(verbose_name='종가')),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stock_analyzer.stock', verbose_name='종목')),
            ],
            options={
                'verbose_name': '일별 주가',
                'verbose_name_plural': '일별 주가',
                'ordering': ['stock__symbol', 'date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
