# Generated by Django 4.1.6 on 2025-07-25 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockdailyprice',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='company_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='market',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stockdailyprice',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdailyprice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockdailyprice',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdailyprice',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdailyprice',
            name='open_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdailyprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analyzer.stock'),
        ),
        migrations.AlterField(
            model_name='stockdailyprice',
            name='volume',
            field=models.BigIntegerField(),
        ),
    ]
